services:
  traefik:
    image: traefik:2
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--tracing=true"
    depends_on:
      - charatunnel
      - charaserver
      - charaweb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik/dynamic:/etc/traefik/dynamic:ro"
      - "./certs:/certs:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.chara-ai.dev`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.priority=200"

  charaserver:
    build:
      context: .
      dockerfile: "Dockerfile.server"
    restart: unless-stopped
    container_name: charaserver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.rule=Host(`server.chara-ai.dev`)"
      - "traefik.http.routers.server.tls=true"
      - "traefik.http.routers.server.priority=70"
      - "traefik.http.services.server.loadbalancer.server.port=3030"

  charaweb:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: unless-stopped
    container_name: charaweb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.rule=Host(`web.chara-ai.dev`)"
      - "traefik.http.routers.web.priority=80"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.services.web.loadbalancer.server.port=3000"

  charatunnel:
    build:
      context: .
      dockerfile: Dockerfile.tunnel
    restart: unless-stopped
    container_name: charatunnel
    volumes:
      - ./config.json:/config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.charatunnel.entrypoints=websecure"
      - "traefik.http.routers.charatunnel.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.chara-ai.dev`)"
      - "traefik.http.routers.charatunnel.tls=true"
      - "traefik.http.routers.charatunnel.priority=100"
      - "traefik.http.services.charatunnel.loadbalancer.server.port=1337"
