FROM oven/bun:1

WORKDIR /app

# Copy package files first for better layer caching
COPY ./package.json .
COPY ./bun.lock .

# Copy source files
COPY . .

WORKDIR /app/apps/landing

# Install dependencies
RUN bun install

# Build the application
RUN bun run build

# Expose default Next.js port
EXPOSE 3000


# Set default command to run the Next.js server
CMD ["bun", "run", "start"]
