# Build stage
FROM oven/bun:latest as build

WORKDIR /app

# Copy all source code and config files
COPY . .

WORKDIR /app/packages/widget/

# Install dependencies
RUN bun install

# Build the app
RUN bun run build

# Expose port
EXPOSE 3000

WORKDIR /app/packages/widget/dist/
# Use Bun's HTML serving capability to serve the static files
# This launches a simple static file server with the index.html as the entry point
CMD ["bun", "index.html"]
