name: Pull Request Checks

on:
  pull_request:
    branches: [main, playground]

jobs:
  pr-checks:
    name: PR Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.bun/install/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install dependencies
        run: bun install

      - name: Check for lockfile changes
        run: |
          if [[ `git status --porcelain bun.lock` ]]; then
            echo "::warning::Lockfile was updated during install. Consider updating the lockfile in your repository."
            git add bun.lock
            echo "Lockfile changes have been staged to prevent CI failures."
          fi

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-pr-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-pr-

      - name: Run lint
        run: bun run lint
        continue-on-error: false

      - name: Run tests
        run: bun run test
        continue-on-error: false

      - name: Run build
        run: bun run build
        continue-on-error: false

      - name: Check for uncommitted changes
        run: |
          # Check for uncommitted changes excluding lockfile
          CHANGES=$(git status --porcelain | grep -v "bun.lock" || true)
          if [[ -n "$CHANGES" ]]; then
            echo "::error::Uncommitted changes detected after build. Please commit all generated files."
            echo "$CHANGES"
            exit 1
          fi

      - name: PR Summary
        if: always()
        run: |
          echo "## Pull Request Checks Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ Linting completed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Tests completed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Build completed" >> $GITHUB_STEP_SUMMARY
          echo "✅ No uncommitted changes detected" >> $GITHUB_STEP_SUMMARY
